export enum AuditActionType {
  // Order actions
  ORDER_CREATE = "ORDER_CREATE",
  ORDER_UPDATE = "ORDER_UPDATE",
  ORDER_DELETE = "ORDER_DELETE",
  ORDER_STATUS_CHANGE = "ORDER_STATUS_CHANGE",
  ORDER_CANCEL = "ORDER_CANCEL",

  // Payment actions
  PAYMENT_CREATE = "PAYMENT_CREATE",
  PAYMENT_UPDATE = "PAYMENT_UPDATE",
  PAYMENT_DELETE = "PAYMENT_DELETE",
  PAYMENT_REFUND = "PAYMENT_REFUND",
  PAYMENT_ADJUST = "PAYMENT_ADJUST",

  // Item actions
  ITEM_ADD = "ITEM_ADD",
  ITEM_UPDATE = "ITEM_UPDATE",
  ITEM_DELETE = "ITEM_DELETE",

  // Queue actions
  QUEUE_ADD = "QUEUE_ADD",
  QUEUE_UPDATE = "QUEUE_UPDATE",
  QUEUE_REMOVE = "QUEUE_REMOVE",
  QUEUE_REORDER = "QUEUE_REORDER",

  // Product actions
  PRODUCT_CREATE = "PRODUCT_CREATE",
  PRODUCT_UPDATE = "PRODUCT_UPDATE",
  PRODUCT_DELETE = "PRODUCT_DELETE",

  // Category actions
  CATEGORY_CREATE = "CATEGORY_CREATE",
  CATEGORY_UPDATE = "CATEGORY_UPDATE",
  CATEGORY_DELETE = "CATEGORY_DELETE",

  // Discount CRUD actions
  DISCOUNT_CREATE = "DISCOUNT_CREATE",
  DISCOUNT_UPDATE = "DISCOUNT_UPDATE",
  DISCOUNT_DELETE = "DISCOUNT_DELETE",
  DISCOUNT_APPLY = "DISCOUNT_APPLY",

  // Promotion actions
  PROMOTION_CREATE = "PROMOTION_CREATE",
  PROMOTION_UPDATE = "PROMOTION_UPDATE",
  PROMOTION_DELETE = "PROMOTION_DELETE",
  PROMOTION_APPLY = "PROMOTION_APPLY",

  // Delivery actions
  DELIVERY_CREATE = "DELIVERY_CREATE",
  DELIVERY_UPDATE = "DELIVERY_UPDATE",
  DELIVERY_DELETE = "DELIVERY_DELETE",

  // Table actions
  TABLE_CREATE = "TABLE_CREATE",
  TABLE_UPDATE = "TABLE_UPDATE",
  TABLE_DELETE = "TABLE_DELETE",

  // Payment method CRUD actions
  PAYMENT_METHOD_CREATE = "PAYMENT_METHOD_CREATE",
  PAYMENT_METHOD_UPDATE = "PAYMENT_METHOD_UPDATE",
  PAYMENT_METHOD_DELETE = "PAYMENT_METHOD_DELETE",

  // Unit actions
  PRODUCTS_UNIT_CREATE = "PRODUCTS_UNIT_CREATE",
  PRODUCTS_UNIT_UPDATE = "PRODUCTS_UNIT_UPDATE",
  PRODUCTS_UNIT_DELETE = "PRODUCTS_UNIT_DELETE",

  // Payment account actions (PromptPay/Bank accounts)
  PAYMENT_ACCOUNT_CREATE = "PAYMENT_ACCOUNT_CREATE",
  PAYMENT_ACCOUNT_UPDATE = "PAYMENT_ACCOUNT_UPDATE",
  PAYMENT_ACCOUNT_ACTIVATE = "PAYMENT_ACCOUNT_ACTIVATE",
  PAYMENT_ACCOUNT_DELETE = "PAYMENT_ACCOUNT_DELETE",

  // Shop profile actions
  SHOP_PROFILE_UPDATE = "SHOP_PROFILE_UPDATE",

  // User actions
  USER_CREATE = "USER_CREATE",
  USER_UPDATE = "USER_UPDATE",
  USER_DELETE = "USER_DELETE",

  // Role actions
  ROLE_CREATE = "ROLE_CREATE",
  ROLE_UPDATE = "ROLE_UPDATE",
  ROLE_DELETE = "ROLE_DELETE",

  // Branch actions
  BRANCH_CREATE = "BRANCH_CREATE",
  BRANCH_UPDATE = "BRANCH_UPDATE",
  BRANCH_DELETE = "BRANCH_DELETE",

  // Stock actions
  STOCK_INGREDIENT_CREATE = "STOCK_INGREDIENT_CREATE",
  STOCK_INGREDIENT_UPDATE = "STOCK_INGREDIENT_UPDATE",
  STOCK_INGREDIENT_DELETE = "STOCK_INGREDIENT_DELETE",
  STOCK_INGREDIENT_UNIT_CREATE = "STOCK_INGREDIENT_UNIT_CREATE",
  STOCK_INGREDIENT_UNIT_UPDATE = "STOCK_INGREDIENT_UNIT_UPDATE",
  STOCK_INGREDIENT_UNIT_DELETE = "STOCK_INGREDIENT_UNIT_DELETE",
  STOCK_ORDER_CREATE = "STOCK_ORDER_CREATE",
  STOCK_ORDER_UPDATE = "STOCK_ORDER_UPDATE",
  STOCK_ORDER_DELETE = "STOCK_ORDER_DELETE",
  STOCK_ORDER_CONFIRM_PURCHASE = "STOCK_ORDER_CONFIRM_PURCHASE",
  STOCK_ORDER_STATUS_UPDATE = "STOCK_ORDER_STATUS_UPDATE",

  // Shift actions
  SHIFT_OPEN = "SHIFT_OPEN",
  SHIFT_CLOSE = "SHIFT_CLOSE",
}

